### ISSUE TITLE
SpiDeviceDriver does not implement spi::FullDuplex

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [esp-rs/esp-idf-hal#198] opened 2022-12-25 21:25 UTC
For example, this is required for [embedded_sdmmc](https://docs.rs/embedded-sdmmc/latest/embedded_sdmmc/index.html) lib

**Comment by dberlin** [comment] 2023-03-15 03:32
Looks like a duplicate of #3 ?

**Comment by dberlin** [comment] 2023-03-15 03:40
The latest version of embedded_sdmmc does not require fullduplex, fwiw

**Comment by Vollbrecht** [comment] 2024-06-21 10:22
closing for #3

**Closed by Vollbrecht** 2024-06-21 10:22 UTC
Labels: duplicate
