### ISSUE TITLE
Creating new UartDriver dosen't work

### ISSUE THREAD

**Issue by leonardodanelutti** [esp-rs/esp-idf-hal#250] opened 2023-05-18 07:23 UTC
Creating a new `UartDriver` panics when calling `uart_intr_config`, this error is logged:

`E (421) uart: uart_intr_config(778): param null`

The problem could be [this](https://github.com/esp-rs/esp-idf-hal/commit/ba9cc4246a18880cdcea5aea21ec3a23edd220f6#r113863437)

**Comment by Vollbrecht** [comment] 2023-05-18 11:19
duplicate of https://github.com/esp-rs/esp-idf-hal/issues/248

**Comment by ivmarkov** [comment] 2023-05-21 17:04
I've commented out this line for now. Yet, we have to come with a long term solution w.r.t. controlling interrupt flags in UART.

**Closed by ivmarkov** 2023-05-21 17:04 UTC

**Comment by ivmarkov** [comment] 2023-05-22 06:12
Yesterday, I've published `V0.41.1` of the crate that has this quick fix checked-in. I also yanked `V0.41.0`.
